[package]
name = "typing_tutor"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
rand = "0.8.5"
dirs = "5.0"
reqwest = { version = "0.11", features = ["blocking"] }
clap = { version = "4.5.60", features = ["derive"] }
